### ISSUE TITLE
Problem with ditcionaries?

### ISSUE THREAD

**Issue by FenixAbbott** [tom-weiland/tcp-udp-networking#12]
Error receiving data from client via UDP: System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

is showing up when I connect via UDP.

**Comment by tom-weiland** [comment]
Join the [Discord server](https://tomweiland.net/discord) and ask for help there.

**Comment by Dudewithoutname** [comment]
On server in Server Send Change
`private static void SendTCPDataToAll(Packet _packet)
        {
            _packet.WriteLength();
            for (int i = 0; i < Server.MaxPlayers; i++)
            {
                Server.clients[i].tcp.SendData(_packet);
            }
        }
        private static void SendTCPDataToAll(int _exceptClient,Packet _packet)
        {
            _packet.WriteLength();
            for (int i = 0; i < Server.MaxPlayers; i++)
            {
                if (i != _exceptClient)
                {
                    Server.clients[i].tcp.SendData(_packet);
                }
            }
        }
        private static void SendUDPDataToAll(Packet _packet)
        {
            _packet.WriteLength();
            for (int i = 0; i < Server.MaxPlayers; i++)
            {
                Server.clients[i].udp.SendData(_packet);
            }
        }
        private static void SendUDPDataToAll(int _exceptClient, Packet _packet)
        {
            _packet.WriteLength();
            for (int i = 0; i < Server.MaxPlayers; i++)
            {
                if (i != _exceptClient)
                {
                    Server.clients[i].udp.SendData(_packet);
                }
            }
        }`
Change in For loops 0 to 1

**Comment by tom-weiland** [comment]
> On server in Server Send
> Change For loops's Ints from 0 to 1

It's _possible_ that this is causing the problem, but there's really no way of knowing for sure without knowing what line of code that error is coming from, which is why I suggested joining the Discord server—troubleshooting is much easier over there.
