### ISSUE TITLE
I made a host and play implementation for those interested

### ISSUE THREAD

**Issue by momozahara** [tom-weiland/tcp-udp-networking#17]
[/momozahara/tcp-udp-networking](https://github.com/momozahara/tcp-udp-networking) have a nice day

**Comment by momozahara** [comment]
oh maybe this is the wrong place

**Comment by tom-weiland** [comment]
I wouldn't exactly describe this as an "issue" :P
If you can share this in the showcase channel on my Discord server if you like.
