### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by flagrama** [tom-weiland/tcp-udp-networking#3]
Would be nice to have a LICENSE file to know what we can and cannot do with this code. As it is, it's under exclusive copyright to you not allowing any one to use, share, or modify it.

Even if that is your intent, it'd be appreciated if it was explicitly stated in a LICENSE file. I feel it is especially important as you are using this in a tutorial series where it is very likely people will be using, sharing, and modifying your code regardless of which license you choose to place it under anyway.

I believe you also said it is based on someone else's code? In which case you'll have to use a compatible license, or possibly the same one as them.

**Comment by tom-weiland** [comment]
It was based on Kevin Kaymak's code, however I never downloaded it from GitHub, only used his tutorials (which didn't have a licence on them). He also personally gave me permission to make my own tutorials :)

**Comment by flagrama** [comment]
Thank you!
