### ISSUE TITLE
WebGL support

### ISSUE THREAD

**Issue by brunoRyckaert** [tom-weiland/tcp-udp-networking#4]
Running a WebGL build (of the example GameClient) throws an exception:

> SocketException: Success
  at System.Net.Sockets.Socket..ctor (System.Net.Sockets.AddressFamily addressFamily, System.Net.Sockets.SocketType socketType, System.Net.Sockets.ProtocolType protocolType) [0x00000] in <00000000000000000000000000000000>:0

WebGL seems to not support TCP and UDP connections due to security reasons.

It would seem that for WebGL, Websockets (WSS) and WebRTC seem to be the way to go.

I know the project is called **tcp-udp-** networking, but would there be any interest in extending support to WSS/WebRTC as well?

I will examine this myself and try to come up with a solution if feasible. In case I'm successful, I'll open a pull request.

I would definitely welcome any feedback on the matter, especially if I'm missing something here and there is a simpler way to achieve WebGL support.

**Comment by tom-weiland** [comment]
Yeah if you're looking to build for the web, as far as I know you'll have to use websockets. Unfortunately I have no experience with those, and at the moment my focus is largely on other projects, so I don't have any plans to add support for WebGL.

That being said, it might be something I'll look into in the future, I just can't currently give you any sort of timeline (I also don't want to make promises that I won't end up keeping).

Additionally, I'd be happy to lend a hand [over on Discord](https://tomweiland.net/discord) with the knowledge that I do have (not sure how much of it actually relates to websockets though).

**Comment by higgy999** [comment]
> Running a WebGL build (of the example GameClient) throws an exception:
> 
> > SocketException: Success
> > at System.Net.Sockets.Socket..ctor (System.Net.Sockets.AddressFamily addressFamily, System.Net.Sockets.SocketType socketType, System.Net.Sockets.ProtocolType protocolType) [0x00000] in <00000000000000000000000000000000>:0
> 
> WebGL seems to not support TCP and UDP connections due to security reasons.
> 
> It would seem that for WebGL, Websockets (WSS) and WebRTC seem to be the way to go.
> 
> I know the project is called **tcp-udp-** networking, but would there be any interest in extending support to WSS/WebRTC as well?
> 
> I will examine this myself and try to come up with a solution if feasible. In case I'm successful, I'll open a pull request.
> 
> I would definitely welcome any feedback on the matter, especially if I'm missing something here and there is a simpler way to achieve WebGL support.

These libraries might be of use. I am incredibly interested in this because I want to make a game that people at my school can run on their Chromebooks.
https://github.com/KillaMaaki/Unity-Netcode.IO

**Comment by tom-weiland** [comment]
Thanks for the links :)

I currently don't have time to look into WebGL support, but I'll make sure to take a look at those repos if/when I decide it's something I want to investigate!
