### ISSUE TITLE
[Question] Would it be possible to have all the server and client code in one Unity Project?

### ISSUE THREAD

**Issue by mxaddict** [tom-weiland/tcp-udp-networking#8]
I noticed that the server needs to have the player and map hitboxes (I'm sure this is to manage collision detection server side)

I'm also assuming that this will eliminate hacks like being able to walk through walls (As for example if you had no geometry on the server it could not tell if a player was wanting to walk through a wall)

So my question is would it be possible to have both server and client in a single project instead of two?

I think this would help in a more long term project (As the assets increase in number and size, you will be having 2 copies of each and the project size will start to grow)

**Comment by tom-weiland** [comment]
You could certainly merge the two projects, but then you'll need to use preprocessor macros to make sure that the server code doesn't end up in the client build (since it's probably not a good idea to hand your server code to players).

The other thing is that the server really only needs the colliders in the scene, and nothing else. If you use the same scene for both, then the server has all this stuff it doesn't need (lights, particle systems, mesh renderers, materials, etc.), and I'm not sure whether or not using the server build option actually excludes those, so it's possible that they'd still add extra overhead.

It might be easier to write a script to export collider data from the client scene and import it on the server, but it's completely up to you.

**Comment by Titan3k** [comment]
If you click server build on the unity build settings, it runs as a command line application, then it dosent render things. You could also jst remove mesh renderers too

**Comment by mxaddict** [comment]
@Titan3k I'm not really concerned about the rendering as you could always just run `-batchmode`, I'm more thinking in terms of the ease of development, as when you add new items, models, maps, you will have to add it once and it will be used for both server and client.

But like @tom-weiland states, this will also mean that the server will be bloated, as in it will have assets that it would never load.

I wonder if the build system can be somehow configured to not include unused assets.

For example if `server side` code could be omitted from the client build and mesh/textures from the server build.

**Comment by mxaddict** [comment]
I wonder if anyone has done this in the past, I guess I'll have to do some digging in the Unity Docs.

**Comment by mxaddict** [comment]
I did some testing with the "server build" option.

Seems it still includes all the assets, the only thing it changed was the binary.

**Comment by tom-weiland** [comment]
> If you click server build on the unity build settings, it runs as a command line application, then it dosent render things

@Titan3k I'm aware, and I mentioned this in my previous reply. The rendering isn't the only concern though—MeshRenders, MeshFilters, Lights, etc. are all components, so even if they're not being rendered, they're using up memory (unless the server build mode actually excludes them, but I don't think it does).

> I wonder if the build system can be somehow configured to not include unused assets.

@mxaddict look into preprocessor macros. You can use those to conditionally compile code, like putting code inside a #if UNITY_EDITOR block will exclude the contents in actual builds. You can use it to exclude code, but as far as I know you can't use it to exclude components on objects (unless you attached them at runtime via code).

**Comment by mxaddict** [comment]
Lets say I have mesh.fbx

And I load it into an object, but I wrap it like this in code:
```csharp
#if !UNITY_STANDALONE_LINUX
// Attach my mesh...
#endif
```

Does this mean that It won't include this mesh in the build data when building for LINUX standalone?

**Comment by mxaddict** [comment]
Also another thing that I just realized, I might actually want the client to have the server code locally as well, incase I want them to be able to host a private game?

Hmmm, but would that make sense... If I don't give them that option, that means I need to provide servers for private game instances if I want to allow players to have private games.

**Comment by tom-weiland** [comment]
The code inside that block won't be included in the build, but you'll still need to reference the mesh somehow.

**Comment by mxaddict** [comment]
Lol, I think I found the solution 🗡️ 

https://assetstore.unity.com/packages/tools/utilities/headless-builder-108317#content
